---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: rhel-7.2
    driver:
      customize:
        memory: 256

suites:
  - name: default
    run_list:
      - recipe[haproxy-cookbook]
    attributes:
    
